name: Website Preview

on: pull_request_target

jobs:
  deploy:
    name: Depoly
    runs-on: ubuntu-latest
    env:
      PULL_REQUEST_NUMBER: ${{ github.event.number }}
    steps:
      - name: Checkout
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn bootstrap

      - name: Build website
        run: yarn website-build

      - name: Deploy Site
        run: |
          export DEPLOY_DOMAIN=https://preview-${PULL_REQUEST_NUMBER}-element-plus.surge.sh
          echo "Deploy to $DEPLOY_DOMAIN"
          npx surge --project ./website-dist --domain $DEPLOY_DOMAIN --token $SURGE_TOKEN
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}

      - name: Deploy has succeeded
        if: ${{ success() }}
        run: |
          export DEPLOY_DOMAIN=https://preview-${PULL_REQUEST_NUMBER}-element-plus.surge.sh
          curl -X POST ${BOT_URL} -H 'Content-Type:application/json' --data-raw '{"botAction":"Preview", "pr":'${PULL_REQUEST_NUMBER}', "url":"'${DEPLOY_DOMAIN}'"}'
        env:
          BOT_URL: ${{ secrets.BOT_URL }}

      - name: Deploy has failed
        if: ${{ failure() }}
        run: |
          curl -X POST ${BOT_URL} -H 'Content-Type:application/json' --data-raw '{"status":"error", "botAction":"Preview", "pr":'${PULL_REQUEST_NUMBER}'}'
        env:
          BOT_URL: ${{ secrets.BOT_URL }}
